#spring.application.name=GatewayService
#server.port=9897
#
#eureka.client.service-url.defaultZone=http://localhost:9091/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.allow-redirects=false
#eureka.client.transport.type=resttemplate
#
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=lb://UserService
#spring.cloud.gateway.routes[0].predicates[0].name=Path
#spring.cloud.gateway.routes[0].predicates[0].args[pattern]=/users/**
#
#spring.cloud.gateway.routes[1].id=property-service
#spring.cloud.gateway.routes[1].uri=lb://PropertyService
#spring.cloud.gateway.routes[1].predicates[0].name=Path
#spring.cloud.gateway.routes[1].predicates[0].args[pattern]=/properties/**



# Gateway Service configuration
spring.application.name=GatewayService
server.port=9897

gateway.service.urls = /users/**,/properties/**

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://localhost:9091/eureka/
eureka.instance.prefer-ip-address=true  
eureka.client.fetch-registry=true
eureka.client.allow-redirects=false
eureka.client.transport.type=resttemplate

spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=reactive

user.service.url=http://172.31.64.1:5555/users/
# Spring Cloud Gateway route configuration

#logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.io.netty.resolver.dns=DEBUG

# User Service Route
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://172.31.64.1:5555/
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
#spring.cloud.gateway.routes[0].predicates[1]=Path=/users/validate

# Property Service Route
spring.cloud.gateway.routes[1].id=property-service
spring.cloud.gateway.routes[1].uri=lb://PropertyService
spring.cloud.gateway.routes[1].predicates[0]=Path=/properties/**
