spring.application.name=UserService
server.port=5555

consumer.service.url=http://ConsumerService/api/ 
user.service.topic=userServiceTopic

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

eureka.client.serviceUrl.defaultZone  = http://localhost:9091/eureka/
eureka.client.instance.preferIpAddress = true